### ISSUE TITLE
test.* functions need descriptions

### ISSUE THREAD

**Issue by pbiecek** [geneticsMiNIng/metR#12]
Add short description related to test.* functions.

**Comment by abrodecka** [comment]
Done in https://github.com/geneticsMiNIng/metR/commit/b915898748acbba53c11c0215465bf7be439fa58 and in https://github.com/geneticsMiNIng/metR/commit/f58fa4174ce27c70c6110755dab862867a5eb2af

**Comment by pbiecek** [comment]
Here are instructions how to add tests to the package
https://pbiecek.gitbooks.io/przewodnik/content/Programowanie/pakiety/nowe_testy.html
they should be in a separate folder `test`

**Comment by pbiecek** [comment]
The function `check_before_using()` shall be converted to a test

**Comment by abrodecka** [comment]
Fix in https://github.com/geneticsMiNIng/metR/commit/555d797dcd3326c1c93312a4f3373d6565e440d0
