### ISSUE TITLE
R code improvements

### ISSUE THREAD

**Issue by pbiecek** [geneticsMiNIng/metR#16]
Function names shall be either camel case or with _
Functions shall be shorter
Please, check this video for more specific guides
https://www.youtube.com/watch?v=rM0MW6YGL5g

**Comment by abrodecka** [comment]
Done in https://github.com/geneticsMiNIng/metR/commit/f58fa4174ce27c70c6110755dab862867a5eb2af

**Comment by pbiecek** [comment]
done
