### ISSUE TITLE
statistical tests need to be somewhere listed and described

### ISSUE THREAD

**Issue by pbiecek** [geneticsMiNIng/metR#20]
In the documentation for `find_DMR()` and in the vigniette there should be a list of implemented statistical tests and short (one/two sentences) description how these tests are working.

**Comment by pbiecek** [comment]
btw: list and descriptions in the vignette 'Comparing all methods' are too short

**Comment by abrodecka** [comment]
Done in https://github.com/geneticsMiNIng/metR/commit/555d797dcd3326c1c93312a4f3373d6565e440d0

**Comment by pbiecek** [comment]
so,
