### ISSUE TITLE
consistent names

### ISSUE THREAD

**Issue by pbiecek** [geneticsMiNIng/metR#24]
Shall all functions that calculates p-values / tests have names with `test_` prefix?

Following functions: reg_corr_mixed, reg_log, reg_mixed
should be renamed into: `test_reg_corr_mixed`, `test_reg_log`, `test_reg_mixed`

**Comment by abrodecka** [comment]
Ready by https://github.com/geneticsMiNIng/metR/commit/79e800990ba6baec1678462ebe63b3cc1ab193df
