### ISSUE TITLE
Identyfikacja genów o zmienionej metylacji - body

### ISSUE THREAD

**Issue by pbiecek** [geneticsMiNIng/metR#5]
Przygotować tabelę, w której każdy wiersz to ludzki gen a kolejne kolumny to:
- nazwa genu w kodzie HGNC
- informacja o współrzędnych genu
- informacja o liczbie markerów metylacyjnych w genie 
- p-wartość opisująca istotność zmiany w genie

**Comment by MarcinKosinski** [comment]
Czy to chodzi o to

# Tools

``` r
library(tidyverse)
library(methylKit)
```

# Preprocessing

``` r, cache = TRUE
list.files("SampleBismarkCG", pattern = "EU|EK", full.names = TRUE) %>%
  sapply(function(file_path){
    #file_name <- strsplit(file_path, "/")[[1]] %>% tail(1)
    read_tsv(file_path) %>% 
      mutate(CHROM = gsub(gsub(`_CHROM`, pattern = "M", replacement = 21),
                          pattern="F", replacement=22)) %>%
      mutate(chrBase = paste0(CHROM, ".", POS),
             chr = CHROM, 
             base = POS,
             strand = REF,
             coverage = DP,
             freqC = round(100*(1 - AF),2),
             freqT = round(100*AF, 2)) %>%
      dplyr::select(chrBase, chr, base, strand, coverage, freqC, freqT) %>%
      write_tsv(paste0(file_path, "_changed"))
    paste0(file_path, "_changed")
}) %>% 
  as.list %>% 
  methRead(sample.id = list("EK", "EU"),
           assembly = "hg18",
           treatment = c(1,0),
           context = "CpG") -> analysis1
```

# Descriptive statistics on samples

``` r, results='asis'
file_names <- list.files("SampleBismarkCG", pattern = "_changed", full.names = TRUE) %>%
  gsub(pattern = "_changed", replacement = "")
seq_along(file_names) %>%
  sapply(function(file_index){

    cat("\n\n")
    cat("## ", tail(strsplit(file_names[file_index], "/")[[1]],1), "\n\n")
    cat("\n\n")

    plot <- capture.output(
      getMethylationStats(analysis1[[file_index]],
                          plot = TRUE, both.strands = FALSE))
      getCoverageStats(analysis1[[file_index]],
                       plot = TRUE, both.strands = FALSE)

    invisible(NULL)
  }) -> dev_null
```

# Filtering samples based on read coverage

``` r
analysis1_filtered <- filterByCoverage(
  analysis1, 
  lo.count = 10,
  lo.perc = NULL,
  hi.count = NULL,
  hi.perc =  99.9
)
```

# Comparative analysis

## Merging samples

``` r
methyl1 <- unite(analysis1_filtered, destrand = FALSE)
```

``` r
methyl1_diff <- calculateDiffMeth(methyl1, num.cores = 8)
```

## Hyper methylated bases

``` r
methyl1_diff_25p_hyper <- getMethylDiff(
  methyl1_diff,
  difference = 25,
  qvalue = 0.01,
  type = "hyper"
)
methyl1_diff_25p_hyper
```

## Hypo methylated bases

``` r
methyl1_diff_25p_hypo <- getMethylDiff(
  methyl1_diff,
  difference = 25,
  qvalue = 0.01,
  type = "hypo"
)
methyl1_diff_25p_hypo
```

## All differentially methylated bases

``` r
methyl1_diff_25p_all <- getMethylDiff(
  methyl1_diff,
  difference = 25,
  qvalue = 0.01,
  type = "hypo"
)
methyl1_diff_25p_all
```

## Distribution of hypo/hyper-methylated bases/regions per chromosome

``` r
diffMethPerChr(methyl1_diff,
               plot = FALSE,
               qvalue.cutoff = 0.01, 
               meth.cutoff = 25)
```

**Comment by MarcinKosinski** [comment]
@pbiecek  z biomart'u wyciągnąłem informacje o współrzędnych genów i ich kodach HGNC. Mam 3 pytania związane z naszą analizą. Jak poniżej

analiza genomowa
================
Marcin Kosiński

-   [Współrzędne genów wraz z ich kodem HGNC](#wsporzedne-genow-wraz-z-ich-kodem-hgnc)
-   [Analizowane dane](#analizowane-dane)
-   [Pytania](#pytania)


### Współrzędne genów wraz z ich kodem HGNC

``` r
# FROM https://bioconductor.org/packages/release/bioc/vignettes/biomaRt/inst/doc/biomaRt.html

library(biomaRt)
ensembl <- useMart("ensembl",
                   dataset = "hsapiens_gene_ensembl")

# head(listAttributes(ensembl),50)
attributes <- c('chromosome_name', 'start_position', 'end_position',
                'gene_biotype', 'hgnc_id', 'hgnc_symbol')

# head(listFilters(ensembl),20)
genes <- getBM(attributes = attributes, mart = ensembl, 
               filter = c('chromosome_name'), value = c(1:22,"X", "Y", "M"))
```

#### Dla jakich chromosomów mamy informacje

``` r
table(genes$chromosome_name)
```


       1   10   11   12   13   14   15   16   17   18   19    2   20   21   22    3 
    5196 2205 3235 2940 1304 2224 2152 2511 2998 1170 2926 3974 1386  835 1319 3010 
       4    5    6    7    8    9    X    Y 
    2505 2868 2863 2868 2354 2242 2365  523 

#### Ile `genów` ma kod HGNC ?

``` r
table(genes$hgnc_symbol != "")
```


    FALSE  TRUE 
    22420 35553 

### Analizowane dane

``` r
library(tidyverse)
library(methylKit)
list.files('SampleBismarkCG', full.names = TRUE, pattern = 'changed') %>%
  as.list %>% 
  methRead(sample.id = list("EK", "EU"),
           assembly = "hg18",
           treatment = c(1,0),
           context = "CpG") -> analysis1
```


    Read 6.6% of 6623585 rows
    Read 28.5% of 6623585 rows
    Read 36.1% of 6623585 rows
    Read 53.9% of 6623585 rows
    Read 70.1% of 6623585 rows
    Read 75.2% of 6623585 rows
    Read 98.0% of 6623585 rows
    Read 6623585 rows and 7 (of 7) columns from 0.271 GB file in 00:00:11

    Read 9.3% of 11355707 rows
    Read 27.0% of 11355707 rows
    Read 42.8% of 11355707 rows
    Read 55.5% of 11355707 rows
    Read 68.7% of 11355707 rows
    Read 72.7% of 11355707 rows
    Read 87.4% of 11355707 rows
    Read 93.5% of 11355707 rows
    Read 11355707 rows and 7 (of 7) columns from 0.464 GB file in 00:00:16

``` r
table(analysis1[[1]]$chr)
```


      chr1  chr10  chr11  chr12  chr13  chr14  chr15  chr16  chr17  chr18  chr19 
    201986 106278 115757 105933  52617  72292  68800 126815 144728  45963 172096 
      chr2  chr20  chr21  chr22   chr3   chr4   chr5   chr6   chr7   chr8   chr9 
    156533  71690  38179  78810 106640  93316 101336 102748 133819  93186 107745 
      chrM   chrX   chrY 
       275  70995    182 

``` r
table(analysis1[[2]]$chr)
```


      chr1  chr10  chr11  chr12  chr13  chr14  chr15  chr16  chr17  chr18  chr19 
    266228 144915 150707 142016  71400  95838  93682 159577 184426  62683 210312 
      chr2  chr20  chr21  chr22   chr3   chr4   chr5   chr6   chr7   chr8   chr9 
    209533  93522  49312  98660 144344 125038 137870 139306 177086 122926 138816 
      chrM   chrX   chrY 
       365  95780    243 

Pytania
=======

-   Czy analizujemy geny ze wszystkich chromosomów?
-   Co zrobić z genami które nie mają kodu `hgnc_symbol`? Pozbyć się ich z analizy?
-   W danych mamy chromosomy `M`, `X` i `Y` - co to jest i czy tego nie brać pod uwagę, zwłaszcza, że dla `M` nie mam annotacji?
