### ISSUE TITLE
Problems with examples

### ISSUE THREAD

**Issue by pbiecek** [geneticsMiNIng/metR#8]
There is some problem with examples, see here:
https://geneticsmining.github.io/metR/reference/find.DMR.html

Looks like part of R code was deleted. 
Examples are lacking of some ')'

**Comment by abrodecka** [comment]
Fixed in https://github.com/geneticsMiNIng/metR/commit/3400086132547d367d2cf9a60d964e4bb9c03c9f and https://github.com/geneticsMiNIng/metR/commit/f58fa4174ce27c70c6110755dab862867a5eb2af :)

**Comment by pbiecek** [comment]
done
